### ISSUE TITLE
The code of modules in ICQ-MA is missing.

### ISSUE THREAD

**Issue by TianQi-777** [YiqinYang/ICQ#2]
Hello, thank you for sharing the latest version of ICQ-MA code, but the code of **modules** is missing, resulting in unable to run MARL version.

**Comment by YiqinYang** [comment]
Thanks for your valuable comment. I missed this file yesterday. I have uploaded the modules files just now. Please try again.

**Comment by TianQi-777** [comment]
Thanks for the timely update, but the **episode_buffer.py** (maybe include **action_selectors.py**) is still missing in **components**

**Comment by YiqinYang** [comment]
Thanks for your reply. I have uploaded the episode_buffer.py and action_selectors.py.

**Comment by TianQi-777** [comment]
It seems that **3s_vs_3z.h5** is broken after being downloaded, but the main body of the code can run correctly (I didn't use **3s_vs_3z.h5**, but wrote some alternative codes). Overall a good job :)

**Comment by YiqinYang** [comment]
We appreciate the comments, and we have uploaded the new 3s_vs_3z.h5. It seems that there are often problems when uploading on Github.
