### ISSUE TITLE
关于ICA-antmaze_mu中ica.py文件中test_bc()函数

### ISSUE THREAD

**Issue by JinmingM** [YiqinYang/ICQ#5]
您好，我在拜读您的代码时，遇到一个问题：
在ICA-antmaze_mu中ica.py文件中test_bc()函数中，tensor_o仅包含observation，而在使用self.vae.decode(tensor_o)时，维度应该是self.obs_dim+2，所以导致以下问题：
RuntimeError: size mismatch, m1: [1 x 45], m2: [47 x 750] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:961

请问该怎么解决？

**Comment by YiqinYang** [comment]
在处理Antmaze任务时，需要提供目标信息，而d4rl并没有提供，需要修改一下d4rl/locomotion/goal_reaching_env.py文件。我已上传到子目录。

**Comment by JinmingM** [comment]
谢谢！
